name: build

on:
  push:
    branches:
      - main

  pull_request:

  schedule:
    - cron: '0 1 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
          - aarch64

    env:
      ARCH: ${{ matrix.arch }} # build target, name required by binary-builder

    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - name: binary-builder
        uses: containerbase/internal-tools@807c465b4f4bc65a76611be701c03f1bfc55e587 # v2.0.1
        with:
          command: binary-builder
          dry-run: ${{github.ref_name != 'main'}}
          token: ${{ secrets.GITHUB_TOKEN }}
