name: build

on:
  push:
    branches:
      - main

  pull_request:

  schedule:
    - cron: '0 1 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
          - aarch64

    env:
      ARCH: ${{ matrix.arch }} # build target, name required by binary-builder

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: binary-builder
        uses: containerbase/internal-tools@959c0a2a2a55b8cdff6790c06443a75eef7d4b31 # v3.0.21
        with:
          command: binary-builder
          dry-run: ${{github.ref_name != 'main'}}
          token: ${{ secrets.GITHUB_TOKEN }}
