name: build

on:
  push:
    branches:
      - main

  pull_request:
  merge_group:

  schedule:
    - cron: '0 1 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref_name }}
  cancel-in-progress: true

env:
  HUSKY: 0

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - run: corepack enable
      - run: pnpm install
      - run: pnpm prettier

  build:
    needs:
      - lint
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
          - aarch64

    env:
      ARCH: ${{ matrix.arch }} # build target, name required by binary-builder

    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: binary-builder
        uses: containerbase/internal-tools@2e58ccb20b6890bd87ef8b3110e61e73adc15d9b # v3.0.90
        with:
          command: binary-builder
          dry-run: ${{github.ref_name != 'main'}}
          token: ${{ secrets.GITHUB_TOKEN }}
