name: build

on:
  push:
    branches:
      - main

  pull_request:
  merge_group:

  schedule:
    - cron: '0 1 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref_name }}
  cancel-in-progress: true

env:
  HUSKY: 0

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: corepack enable
      - run: pnpm install
      - run: pnpm prettier

  build:
    needs:
      - lint
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
          - aarch64

    env:
      ARCH: ${{ matrix.arch }} # build target, name required by binary-builder

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: binary-builder
        uses: containerbase/internal-tools@fd19a9e4e99f83adf8ec2529ef1276b626d6785f # v3.4.45
        with:
          command: binary-builder
          dry-run: ${{github.ref_name != 'main'}}
          token: ${{ secrets.GITHUB_TOKEN }}
